import { useEffect, useState, FormEvent } from "react";
import "./styles/clinical-alemania.css";
import { BRAND, specialties, doctors, services, insurers, faqs } from "./data/clinicalContent";
import { isValidRut, formatRut } from "./lib/rut";
import { Appointment, findPatient, savePatient, getAvailability, bookAppointment, myAppointments, cancelAppointment, submitFeedback, findFeedback, Feedback } from "./lib/clinicalApi";

const ROUTES: [string, string][] = [["inicio", "Inicio"], ["reservar", "Reservar hora"], ["mis-citas", "Mis citas"], ["especialidades", "Especialidades"], ["servicios", "Servicios"], ["convenios", "Convenios"], ["contacto", "Contacto"], ["reclamos", "Reclamos y sugerencias"], ["ayuda", "Ayuda"]];
function useRoute() { const get = () => (location.hash.replace("#/", "") || "inicio"); const [r, setR] = useState(get()); useEffect(() => { const f = () => { setR(get()); window.scrollTo(0, 0); }; window.addEventListener("hashchange", f); return () => window.removeEventListener("hashchange", f); }, []); return r; }
const Logo = () => <a className="logo" href="#/inicio" aria-label={`${BRAND} - inicio`}><svg width="40" height="40" viewBox="0 0 40 40" aria-hidden="true"><path d="M15 3h10v12h12v10H25v12H15V25H3V15h12z" fill="none" stroke="#fff" strokeWidth="3" strokeLinejoin="round" /></svg><span><small>Clínica</small>Alemania</span></a>;
const todayISO = () => new Date().toISOString().slice(0, 10);

function Booking() {
  const [step, setStep] = useState(1), [rut, setRut] = useState(""), [consent, setConsent] = useState(false), [p, setP] = useState({ name: "", email: "", phone: "", insurer: "FONASA" }), [isNew, setIsNew] = useState(false), [spec, setSpec] = useState(specialties[0].code), [doc, setDoc] = useState(""), [date, setDate] = useState(todayISO()), [time, setTime] = useState(""), [err, setErr] = useState(""), [done, setDone] = useState<Appointment | null>(null);
  const docs = doctors.filter((d) => d.specialty === spec), slots = doc ? getAvailability(doc, date) : [];
  const identify = (e: FormEvent) => { e.preventDefault(); setErr(""); if (!isValidRut(rut)) return setErr("El RUT ingresado no es válido. Revisa el dígito verificador."); if (!consent) return setErr("Debes aceptar el uso de tus datos para agendar."); const found = findPatient(rut); if (found) { setP(found); setIsNew(false); setStep(3); } else { setIsNew(true); setStep(2); } };
  const register = (e: FormEvent) => { e.preventDefault(); setErr(""); try { savePatient({ rut, ...p }); setStep(3); } catch (x) { setErr((x as Error).message); } };
  const confirm = () => { setErr(""); try { setDone(bookAppointment(rut, doc, date, time)); setStep(4); } catch (x) { setErr((x as Error).message); } };
  if (done) { const d = doctors.find((x) => x.id === done.doctorId)!; return <div className="card"><h2>Hora confirmada</h2><div className="msg ok">Código de reserva: <strong>{done.id}</strong></div><p>{done.patientName} · RUT {done.rut}<br />{d.name} · {d.room}<br />{done.date} a las {done.time} hrs</p><a className="btn" href="#/mis-citas">Ver mis citas</a></div>; }
  return <div><div className="steps">{["Identificación", "Datos", "Hora", "Confirmación"].map((s, i) => <span key={s} className={step === i + 1 ? "on" : ""}>{i + 1}. {s}</span>)}</div>{err && <div className="msg err" role="alert">{err}</div>}{step === 1 && <form className="card" onSubmit={identify}><label htmlFor="rut">RUT</label><input id="rut" value={rut} onChange={(e) => setRut(formatRut(e.target.value))} placeholder="12.345.678-5" autoComplete="off" /><label><input type="checkbox" style={{ width: "auto" }} checked={consent} onChange={(e) => setConsent(e.target.checked)} /> Acepto que mis datos se usen solo para gestionar mi reserva (prototipo de desarrollo).</label><p><button className="btn">Continuar</button></p></form>}{step === 2 && <form className="card" onSubmit={register}><div className="msg info">No encontramos el RUT {rut}. Completa tus datos para crear tu ficha.</div><label htmlFor="n">Nombre completo</label><input id="n" required value={p.name} onChange={(e) => setP({ ...p, name: e.target.value })} /><label htmlFor="e">Correo</label><input id="e" type="email" required value={p.email} onChange={(e) => setP({ ...p, email: e.target.value })} /><label htmlFor="t">Teléfono</label><input id="t" required value={p.phone} onChange={(e) => setP({ ...p, phone: e.target.value })} /><label htmlFor="i">Previsión</label><select id="i" value={p.insurer} onChange={(e) => setP({ ...p, insurer: e.target.value })}>{insurers.map((i) => <option key={i.name}>{i.name}</option>)}</select><p><button className="btn">Guardar y continuar</button></p></form>}{step === 3 && <div className="card">{!isNew && <div className="msg ok">Hola, {p.name}. Elige tu hora.</div>}<label htmlFor="s">Especialidad</label><select id="s" value={spec} onChange={(e) => { setSpec(e.target.value); setDoc(""); setTime(""); }}>{specialties.map((s) => <option key={s.code} value={s.code}>{s.name}</option>)}</select><label htmlFor="d">Profesional</label><select id="d" value={doc} onChange={(e) => { setDoc(e.target.value); setTime(""); }}><option value="">Selecciona…</option>{docs.map((d) => <option key={d.id} value={d.id}>{d.name} · {d.room}</option>)}</select><label htmlFor="f">Fecha</label><input id="f" type="date" min={todayISO()} value={date} onChange={(e) => { setDate(e.target.value); setTime(""); }} /><label>Horarios disponibles</label><div className="slots">{doc && slots.length === 0 && <span>Sin horarios para esta fecha.</span>}{slots.map((t) => <button type="button" key={t} className="slot" aria-pressed={time === t} onClick={() => setTime(t)}>{t}</button>)}</div><p><button className="btn" disabled={!doc || !time} onClick={confirm}>Confirmar hora</button></p></div>}</div>;
}
function MyAppointments() { const [rut, setRut] = useState(""), [list, setList] = useState<Appointment[] | null>(null), [err, setErr] = useState(""); const load = () => { setErr(""); if (!isValidRut(rut)) { setList(null); return setErr("RUT inválido."); } setList(myAppointments(rut)); }; return <div><div className="card"><label htmlFor="r">Ingresa tu RUT</label><input id="r" value={rut} onChange={(e) => setRut(formatRut(e.target.value))} /><p><button className="btn" onClick={load}>Consultar</button></p></div>{err && <div className="msg err">{err}</div>}{list && (list.length === 0 ? <div className="msg info">No hay citas registradas.</div> : <table><thead><tr><th>Código</th><th>Fecha</th><th>Hora</th><th>Profesional</th><th>Estado</th><th></th></tr></thead><tbody>{list.map((a) => <tr key={a.id}><td>{a.id}</td><td>{a.date}</td><td>{a.time}</td><td>{doctors.find((d) => d.id === a.doctorId)?.name}</td><td>{a.status}</td><td>{a.status === "confirmada" && <button className="btn ghost" onClick={() => { cancelAppointment(a.id); load(); }}>Anular</button>}</td></tr>)}</tbody></table>)}</div>; }
function Contact({ kind }: { kind: "contacto" | "reclamos" }) { const [f, setF] = useState({ kind: kind === "contacto" ? "Consulta" : "Reclamo", name: "", email: "", message: "" }), [sent, setSent] = useState<Feedback | null>(null), [folio, setFolio] = useState(""), [found, setFound] = useState<Feedback | null | undefined>(undefined); const send = (e: FormEvent) => { e.preventDefault(); setSent(submitFeedback(f)); }; return <div className="grid"><form className="card" onSubmit={send}><h3>{kind === "contacto" ? "Escríbenos" : "Reclamos y sugerencias"}</h3><div className="msg info">No incluyas datos clínicos ni diagnósticos.</div>{kind === "reclamos" && <><label htmlFor="k">Tipo</label><select id="k" value={f.kind} onChange={(e) => setF({ ...f, kind: e.target.value })}>{["Reclamo", "Sugerencia", "Felicitación"].map((k) => <option key={k}>{k}</option>)}</select></>}<label htmlFor="cn">Nombre</label><input id="cn" required value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /><label htmlFor="ce">Correo</label><input id="ce" type="email" required value={f.email} onChange={(e) => setF({ ...f, email: e.target.value })} /><label htmlFor="cm">Mensaje</label><textarea id="cm" rows={5} required value={f.message} onChange={(e) => setF({ ...f, message: e.target.value })} /><p><button className="btn">Enviar</button></p>{sent && <div className="msg ok">Recibido. Tu folio es <strong>{sent.folio}</strong>.</div>}</form><div className="card"><h3>Seguimiento por folio</h3><label htmlFor="fo">Folio</label><input id="fo" value={folio} onChange={(e) => setFolio(e.target.value)} /><p><button className="btn ghost" onClick={() => setFound(findFeedback(folio) ?? null)}>Buscar</button></p>{found && <div className="msg ok">{found.kind} · Estado: {found.status}</div>}{found === null && <div className="msg err">Folio no encontrado.</div>}<h3>Canales (ficticios)</h3><p>contacto@clinicaalemania.example<br />Lunes a viernes 08:00–19:00<br />Sede Central (simulada)</p></div></div>; }
function Page({ route }: { route: string }) { switch (route) { case "reservar": return <><h2>Reservar hora</h2><Booking /></>; case "mis-citas": return <><h2>Mis citas</h2><MyAppointments /></>; case "especialidades": return <><h2>Especialidades</h2><div className="grid">{specialties.map((s) => <div className="card" key={s.code}><small>Código {s.code}</small><h3>{s.name}</h3><p>{s.description}</p><a className="btn ghost" href="#/reservar">Reservar</a></div>)}</div></>; case "servicios": return <><h2>Servicios</h2><div className="grid">{services.map((s) => <div className="card" key={s.title}><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></>; case "convenios": return <><h2>Seguros y convenios</h2><div className="grid">{insurers.map((s) => <div className="card" key={s.name}><h3>{s.name}</h3><p>{s.text}</p></div>)}</div></>; case "contacto": return <><h2>Contacto</h2><Contact kind="contacto" /></>; case "reclamos": return <><h2>Reclamos y sugerencias</h2><Contact kind="reclamos" /></>; case "ayuda": return <><h2>Preguntas frecuentes</h2>{faqs.map((f) => <details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</>; case "privacidad": return <><h2>Privacidad</h2><p>Solo se guardan datos mínimos para gestionar reservas, con tu consentimiento. No se almacenan datos clínicos.</p></>; case "terminos": return <><h2>Términos de uso</h2><p>Sitio en desarrollo. Profesionales y salas son datos simulados.</p></>; case "accesibilidad": return <><h2>Accesibilidad</h2><p>Navegación por teclado, etiquetas en formularios y contraste adecuado.</p></>; default: return <><section className="hero" style={{ margin: "-36px 0 32px" }}><div className="wrap"><h1>Tu salud, en buenas manos</h1><p>Reserva tu hora en minutos con tu RUT, elige especialidad y profesional.</p><a className="btn light" href="#/reservar">Reservar hora</a></div></section><h2>Accesos frecuentes</h2><div className="grid">{[["reservar", "Reservar hora"], ["mis-citas", "Anular o ver mis citas"], ["especialidades", "Ver especialidades"], ["reclamos", "Reclamos y sugerencias"]].map(([h, t]) => <a key={h} className="card" href={`#/${h}`}><h3>{t}</h3></a>)}</div><div className="msg info" style={{ marginTop: 24 }}>Emergencias reales: contacta a los servicios de emergencia oficiales de tu zona.</div></>; } }
export default function App() { const route = useRoute(); return <><a className="skip" href="#main">Saltar al contenido</a><div className="alert-bar">Sitio en desarrollo · Datos de profesionales simulados</div><header className="top"><div className="wrap nav"><Logo /><nav aria-label="Principal"><ul>{ROUTES.map(([h, t]) => <li key={h}><a href={`#/${h}`} aria-current={route === h ? "page" : undefined}>{t}</a></li>)}</ul></nav></div></header><main id="main"><div className="wrap"><Page route={route} /></div></main><footer><div className="wrap"><div className="fgrid"><div><h4>{BRAND}</h4><p>Gestión de citas y atención al paciente.</p></div><div><h4>Pacientes</h4><ul>{ROUTES.slice(1, 5).map(([h, t]) => <li key={h}><a href={`#/${h}`}>{t}</a></li>)}</ul></div><div><h4>Ayuda</h4><ul><li><a href="#/ayuda">Preguntas frecuentes</a></li><li><a href="#/contacto">Contacto</a></li><li><a href="#/reclamos">Reclamos y sugerencias</a></li></ul></div><div><h4>Legal</h4><ul><li><a href="#/privacidad">Privacidad</a></li><li><a href="#/terminos">Términos</a></li><li><a href="#/accesibilidad">Accesibilidad</a></li></ul></div></div><p className="copy">© 2026 {BRAND}. Todos los derechos reservados.</p></div></footer></>; }
